spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${CLIENT-ID}
            client-secret: ${CLIENT-SECRET}
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: ${ISSUER_URI}